version: "3.2"
services:
  car-listing-producer:
    build:
      context: ./
      dockerfile: ./car-listing-producer/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_HOST: kafka:9092

  car-listing-consumer:
    build:
      context: ./
      dockerfile: ./car-listing-consumer/Dockerfile
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8081:8081"
    environment:
      KAFKA_HOST: kafka:9092
      ELASTICSEARCH_HOST: elasticsearch:9200

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1